#!/usr/bin/env python3
"""
Memory Manager - Raffles IT Kit
===============================
Deterministic read/write engine for the kit's two-tier memory:

  memory/short_term.json  - volatile working memory, cleared per session
  memory/long_term.json   - durable facts/decisions that survive sessions
  memory/MEMORY.md        - human-readable index of long-term memory

Agents and the /memory workflow call this script so memory operations are
consistent and side-effect free. Standard library only.

Usage:
    python scripts/memory_manager.py init
    python scripts/memory_manager.py save --type decision --title "Use Opus 4.8 for orchestration" \\
        --content "Heavy agents run on claude-opus-4-8 as of 2026-06." --tags models,config
    python scripts/memory_manager.py recall "opus"
    python scripts/memory_manager.py list [--type decision]
    python scripts/memory_manager.py show <id>
    python scripts/memory_manager.py forget <id>
    python scripts/memory_manager.py session-clear
    python scripts/memory_manager.py stats
"""

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

MEMORY_DIR = Path(__file__).resolve().parent.parent / "memory"
LONG_TERM = MEMORY_DIR / "long_term.json"
SHORT_TERM = MEMORY_DIR / "short_term.json"
INDEX_MD = MEMORY_DIR / "MEMORY.md"

VALID_TYPES = {"decision", "preference", "fact", "project", "reference", "convention"}

SHORT_TERM_TEMPLATE = {
    "version": "1.0",
    "description": "Short-term agent memory — cleared between sessions",
    "context": {},
    "task_history": [],
    "active_agents": [],
}


def _today() -> str:
    return date.today().isoformat()


def _load_long_term() -> dict:
    if not LONG_TERM.exists():
        return {
            "version": "1.0",
            "description": "Long-term memory — persists across sessions",
            "updated": _today(),
            "entries": [],
        }
    with open(LONG_TERM, "r", encoding="utf-8") as f:
        return json.load(f)


def _save_long_term(store: dict) -> None:
    store["updated"] = _today()
    with open(LONG_TERM, "w", encoding="utf-8") as f:
        json.dump(store, f, indent=2, ensure_ascii=False)
        f.write("\n")
    _rebuild_index(store)


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:48] or "memory"


def _unique_id(store: dict, title: str) -> str:
    base = _slugify(title)
    existing = {e["id"] for e in store["entries"]}
    if base not in existing:
        return base
    n = 2
    while f"{base}-{n}" in existing:
        n += 1
    return f"{base}-{n}"


def _rebuild_index(store: dict) -> None:
    lines = [
        "# MEMORY.md — Long-term memory index",
        "",
        "> Auto-generated by `scripts/memory_manager.py`. One line per durable memory.",
        f"> {len(store['entries'])} entr{'y' if len(store['entries']) == 1 else 'ies'} · updated {store.get('updated', _today())}",
        "",
    ]
    by_type: dict = {}
    for e in store["entries"]:
        by_type.setdefault(e.get("type", "fact"), []).append(e)
    for t in sorted(by_type):
        lines.append(f"## {t}")
        lines.append("")
        for e in by_type[t]:
            snippet = " ".join(e.get("content", "").split())
            if len(snippet) > 90:
                snippet = snippet[:90].rstrip() + "…"
            tags = e.get("tags", [])
            tag_str = f" _(tags: {', '.join(tags)})_" if tags else ""
            lines.append(f"- **{e.get('title', e['id'])}** (`{e['id']}`) — {snippet}{tag_str}")
        lines.append("")
    with open(INDEX_MD, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def cmd_init(_args) -> int:
    MEMORY_DIR.mkdir(parents=True, exist_ok=True)
    if not SHORT_TERM.exists():
        with open(SHORT_TERM, "w", encoding="utf-8") as f:
            json.dump(SHORT_TERM_TEMPLATE, f, indent=2, ensure_ascii=False)
            f.write("\n")
        print(f"created {SHORT_TERM.name}")
    store = _load_long_term()
    _save_long_term(store)
    print(f"memory initialized in {MEMORY_DIR}")
    return 0


def cmd_save(args) -> int:
    if args.type not in VALID_TYPES:
        print(f"error: --type must be one of {sorted(VALID_TYPES)}", file=sys.stderr)
        return 2
    store = _load_long_term()
    tags = [t.strip() for t in (args.tags or "").split(",") if t.strip()]
    related = [r.strip() for r in (args.related or "").split(",") if r.strip()]
    entry_id = _unique_id(store, args.title)
    entry = {
        "id": entry_id,
        "type": args.type,
        "title": args.title,
        "content": args.content,
        "tags": tags,
        "related": related,
        "created": _today(),
        "updated": _today(),
    }
    store["entries"].append(entry)
    _save_long_term(store)
    print(f"saved: {entry_id}")
    return 0


def _matches(entry: dict, query: str) -> bool:
    q = query.lower()
    haystack = " ".join(
        [entry.get("title", ""), entry.get("content", ""), " ".join(entry.get("tags", [])), entry.get("type", "")]
    ).lower()
    return q in haystack


def cmd_recall(args) -> int:
    store = _load_long_term()
    hits = [e for e in store["entries"] if _matches(e, args.query)]
    if not hits:
        print(f"no memory matches '{args.query}'")
        return 0
    print(f"=== {len(hits)} match(es) for '{args.query}' ===\n")
    for e in hits:
        print(f"[{e['type']}] {e['title']}  ({e['id']})")
        print(f"  {e['content']}")
        if e.get("tags"):
            print(f"  tags: {', '.join(e['tags'])}")
        print()
    return 0


def cmd_list(args) -> int:
    store = _load_long_term()
    entries = store["entries"]
    if args.type:
        entries = [e for e in entries if e.get("type") == args.type]
    if not entries:
        print("(no entries)")
        return 0
    for e in entries:
        print(f"{e['id']:<50} [{e['type']}] {e['title']}")
    return 0


def cmd_show(args) -> int:
    store = _load_long_term()
    for e in store["entries"]:
        if e["id"] == args.id:
            print(json.dumps(e, indent=2, ensure_ascii=False))
            return 0
    print(f"error: no entry with id '{args.id}'", file=sys.stderr)
    return 1


def cmd_forget(args) -> int:
    store = _load_long_term()
    before = len(store["entries"])
    store["entries"] = [e for e in store["entries"] if e["id"] != args.id]
    if len(store["entries"]) == before:
        print(f"error: no entry with id '{args.id}'", file=sys.stderr)
        return 1
    _save_long_term(store)
    print(f"forgot: {args.id}")
    return 0


def cmd_session_clear(_args) -> int:
    with open(SHORT_TERM, "w", encoding="utf-8") as f:
        json.dump(SHORT_TERM_TEMPLATE, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print("short-term memory cleared")
    return 0


def cmd_stats(_args) -> int:
    store = _load_long_term()
    by_type: dict = {}
    for e in store["entries"]:
        by_type[e.get("type", "fact")] = by_type.get(e.get("type", "fact"), 0) + 1
    print(f"long-term entries: {len(store['entries'])}")
    for t in sorted(by_type):
        print(f"  {t}: {by_type[t]}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Raffles IT Kit memory manager")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("init", help="create memory files if missing")

    p_save = sub.add_parser("save", help="store a long-term memory")
    p_save.add_argument("--type", required=True, help=f"one of {sorted(VALID_TYPES)}")
    p_save.add_argument("--title", required=True)
    p_save.add_argument("--content", required=True)
    p_save.add_argument("--tags", default="", help="comma-separated")
    p_save.add_argument("--related", default="", help="comma-separated entry ids")

    p_recall = sub.add_parser("recall", help="search long-term memory")
    p_recall.add_argument("query")

    p_list = sub.add_parser("list", help="list long-term memory")
    p_list.add_argument("--type", default=None)

    p_show = sub.add_parser("show", help="print one entry as JSON")
    p_show.add_argument("id")

    p_forget = sub.add_parser("forget", help="delete one entry")
    p_forget.add_argument("id")

    sub.add_parser("session-clear", help="reset short-term memory")
    sub.add_parser("stats", help="summary counts")

    args = parser.parse_args()
    handlers = {
        "init": cmd_init,
        "save": cmd_save,
        "recall": cmd_recall,
        "list": cmd_list,
        "show": cmd_show,
        "forget": cmd_forget,
        "session-clear": cmd_session_clear,
        "stats": cmd_stats,
    }
    return handlers[args.command](args)


if __name__ == "__main__":
    raise SystemExit(main())
